services:
  laravel-app:
    image: ghcr.io/zer0xff/laravel-app-docker:latest
    container_name: laravel-app
    ports:
      - "8000:80"
    environment:
      - APP_NAME=laravel_app
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - GIT_URL=SET_URL
      - GIT_BRANCH=origin/main
